### ISSUE TITLE
0.14.0 issue in createResolveable?

### ISSUE THREAD

**Issue by edward653** [lenkan/deno-amqp#17]
Working on upgrading a project I have in progress to latest Deno and library versions. What was working fine earlier (sadly I do not recall the Deno version), is now not compiling, and I do not think I am the cause (though I will admit to not being a Typescript expert by any stretch!!)

Deno version is:

deno 1.6.2 (release, x86_64-apple-darwin)
v8 8.8.278.2
typescript 4.1.3

The error trace is:

error: TS2322 [ERROR]: Type '(value: T | PromiseLike<T>) => void' is not assignable to type '(value?: T | PromiseLike<T> | Promise<T> | undefined) => void'.
  Types of parameters 'value' and 'value' are incompatible.
    Type 'T | PromiseLike<T> | Promise<T> | undefined' is not assignable to type 'T | PromiseLike<T>'.
      Type 'undefined' is not assignable to type 'T | PromiseLike<T>'.
    resolveFun = resolve;
    ~~~~~~~~~~
    at https://deno.land/x/amqp@v0.14.0/src/resolvable.ts:13:5

**Comment by edward653** [comment]
Grabbing master and running deno test src/   produces the very same error:

$ deno test src/
Check <blah>/amqp/$deno$test.ts
error: TS2322 [ERROR]: Type '(value: T | PromiseLike<T>) => void' is not assignable to type '(value?: T | PromiseLike<T> | Promise<T> | undefined) => void'.
  Types of parameters 'value' and 'value' are incompatible.
    Type 'T | PromiseLike<T> | Promise<T> | undefined' is not assignable to type 'T | PromiseLike<T>'.
      Type 'undefined' is not assignable to type 'T | PromiseLike<T>'.
    resolveFun = resolve;
    ~~~~~~~~~~
    at <blah>/amqp/src/resolvable.ts:13:5

**Comment by edward653** [comment]
Created PR https://github.com/lenkan/deno-amqp/pull/18 to potentially fix this
