### ISSUE TITLE
assertNotClosed throws uncatchable errors?

### ISSUE THREAD

**Issue by bramtechs** [lenkan/deno-amqp#49]
Hello,
I can't figure out how to catch the following error which seems to be thrown from a different event loop entirely.
```
error: Uncaught (in promise) Error: Channel 1 closed by server - 404 NOT_FOUND - no queue 'ambient_temps_765c545d' in vhost '/' - caused by 'basic.consume'
      throw new Error(serializeChannelError(channel, frame.payload.args));
            ^
    at assertNotClosed (https://raw.githubusercontent.com/ohroy/deno-amqp/refs/heads/master/src/amqp_multiplexer.ts:87:13)
    at Object.handle (https://raw.githubusercontent.com/ohroy/deno-amqp/refs/heads/master/src/amqp_multiplexer.ts:165:9)
    at emit (https://raw.githubusercontent.com/ohroy/deno-amqp/refs/heads/master/src/amqp_multiplexer.ts:133:24)
    at listen (https://raw.githubusercontent.com/ohroy/deno-amqp/refs/heads/master/src/amqp_multiplexer.ts:109:9)
    at eventLoopTick (ext:core/01_core.js:175:7)
```
The program should not crash when the queue is not found.
I desperately tried putting everything inside a try-catch without success.

The relevant code inside of a class:
```ts
// -- snip --
    async collect(name: string): Promise<Optional<SensorTemp>> {
        let connection: AmqpConnection | undefined;
        if (!name) {
            throw new DomainException('Sensor name is required');
        }

        try {
            connection = await this.connectToRabbitMQ();
            const channel = await connection.openChannel();
            const result = await new Promise<Optional<SensorTemp>>((accept, reject) => {
                try {
                    channel.consume({ queue: name }, (args, _, data) => {
                        try {
                            const message = new TextDecoder().decode(data);
                            const entity = SensorTempRabbitRepository.mapMessageToEntity(name, message);
                            // Do not acknowledge the message to allow other consumers to process it without waiting for a new sample
                            channel.nack({ deliveryTag: args.deliveryTag, multiple: false, requeue: true }).then(() => {
                                accept(entity);
                            });
                        } catch (error) {
                            reject(error);
                        }
                    });
                } catch (error) {
                    reject(error);
                }
            });
            await channel.close();
            return result;
        } catch (error) {
            console.error(`Error collecting temperature: ${error}`);
        } finally {
            await connection?.close();
        }
        return Optional.empty<SensorTemp>();
    }
// -- snip --
```
Please let me know if I am doing something wrong or if this is intended behavior.

Thank you for your time.

**Comment by lenkan** [comment]
In your example code, you are not awaiting the promise that is returned from `consume`. As you can see here [here](https://github.com/lenkan/deno-amqp/blob/63cbcb46f9cb815885f798845fe17496dd3c7d47/src/amqp_channel.ts#L266-L285), the `consume` method is asynchronuous. I believe that you would get an immediate `CHANNEL_CLOSE` reply from the broker when you are trying to consume from a queue that does not exist. Therefore that promise will reject. Since that rejection is not handled, your process will crash.

**Comment by bramtechs** [comment]
This was indeed what caused the crash, an oversight on my part. Thank you for your help!
For others reading, this is my reworked code from above:
```ts
async collect(name: string): Promise<Optional<SensorTemp>> {
        let connection: AmqpConnection | undefined;
        if (!name) {
            throw new DomainException('Sensor name is required');
        }

        let result = Optional.empty<SensorTemp>();
        try {
            connection = await this.connectToRabbitMQ();
            const channel = await connection.openChannel();
            await channel.consume({ queue: name }, async (args, _, data) => {
                const message = new TextDecoder().decode(data);
                const entity = SensorTempRabbitRepository.mapMessageToEntity(
                    name,
                    message,
                );
                result = entity;

                // Do not acknowledge the message to allow other consumers to process it without waiting for a new sample
                await channel
                    .nack({
                        deliveryTag: args.deliveryTag,
                        multiple: false,
                        requeue: true,
                    });
            });
            await channel.close();
        } catch (error) {
            console.error(`Error collecting temperature: ${error}`);
        }
        return result;
    }
```
